#!/bin/sh

#
# This script is a fake 'agent-smith' program.
#
# When 'upgrade' is sent to 'agent-smith' and it is given a nova-agent
# tarball to upgrade to, it'll download it, and just call agent-smith's
# init script with 'restart'.  agent-smith's init script will de-install
# agent-smith, untar the new tarball, and then try to start
# /usr/sbin/agent-smith
#
# So, we need this program to be installed as /usr/sbin/agent-smith,
# which will take care of removing agent-smith's init script, install
# nova-agent's init script, and then run it.  When done, this script
# will remove itself.

rm -f /etc/init.d/agent-smith
rm -f /etc/init.d/agent-smith.init

cp -p /usr/share/nova-agent/etc/nova-agent.init /etc/init.d/nova-agent

sh /etc/init.d/nova-agent start

rm -f /usr/sbin/agent-smith

exit 0
