#!/bin/sh

nova_agent="/usr/sbin/nova-agent"
agent_config="/usr/share/nova-agent/nova-agent.py"
pidfile="/var/run/nova-agent.pid"
logfile="/var/log/nova-agent.log"
loglevel="info"

do_start() {
  ${nova_agent} -q -p ${pidfile} -o ${logfile} -l ${loglevel} ${agent_config}
}

do_stop() {
  kill `cat ${pidfile}`
  rm -f ${pidfile}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
    do_start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

